### ISSUE TITLE
add drive issue

### ISSUE THREAD

**Issue by raju010193** [quadrifoglio/go-qemu#1]
img, err := qemu.OpenImage("debian.qcow2")
	if err != nil {
		log.Fatal(err)
	}
	
	m := qemu.NewMachine(1, 512) // 1 CPU, 512MiB RAM
    m.AddDrive(img)
	
	pid, err := m.Start("x86_64", true) // x86_64 arch (using qemu-system-x86_64), with kvm
	if err != nil {
		log.Fatal(err)
	}
	
	fmt.Println("QEMU started on PID", pid)

i am getting error like

/main.go:65:21: not enough arguments in call to m.Start
	have (string, bool)
	want (string, bool, func(string))

**Comment by quadrifoglio** [comment]
Hi,

The README is not up to date, sorry.
The `Start` functions expects an additional parameter, a callback function that will be asynchronously invoked in case QEMU fails to run and outputs something in `stderr`.

Here is an example usage:

```go
pid, err := m.Start("x86_64", true, func(stderr string) {
    log.Println("qemu stderr:", stderr)
})

if err != nil {
    log.Fatalf(err)
}
```

**Comment by raju010193** [comment]
Did you know how to connect Unix path using go and install the software packages and etc..

**Comment by quadrifoglio** [comment]
Not sure to understand what you mean mdr

**Comment by raju010193** [comment]
actually i want to access the vm using unix path. is it possible? if possible, do you know how to do please tel me

**Comment by quadrifoglio** [comment]
If you're talking about accessing the QMP through a unix socket, take a look at [go-qmp](https://github.com/quadrifoglio/go-qmp)
